apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sandbox-frontendapp-svc.yaml
- sandbox-frontendapp-svc-preview.yaml
- sandbox-frontendapp-rollout.yaml
- sandbox-frontendapp-route.yaml
- sandbox-frontendapp-route-preview.yaml


images:
- name: harbor.hqokd.nshcloud.com/sandbox-frontendapp/sandbox-frontendapp
  newTag: "v3.0"
