apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sandbox-backendapp-svc.yaml
- sandbox-backendapp-svc-preview.yaml
- sandbox-backendapp-rollout.yaml
- sandbox-backendapp-route.yaml
- sandbox-backendapp-route-preview.yaml


images:
- name: harbor.hqokd.nshcloud.com/sandbox-backendapp/sandbox-backendapp
  newTag: "v3.3"
